export default [
    {   title: "Beginner",
        info: "Beginner является твердым фундаментом, который пригодится для всех последующих уровней",
        learn: ["Алфавиту", "Как правильно произносить звуки", "Понимать английскую речь", "Говорить на простые темы", "Самостоятельно читать изи тексты", "Как использовать простые выражения", "Как строить диалоги в жизни", "Самостоятельно писать простые предложения путём использования вокабуляра и грамматики", "Развишь в себе личностные качества и любознательость"],
        syllabus: ["Parts of speech", "Nouns Verbs", "Adjectives Numerals", "Adverbs Personal Pronouns", "Subject Pronouns", "Object Pronouns To be", "am is are", "Possesive abjectivess", "Articles Countable and Uncountable nouns", "Singular an Plural nouns"] ,
        open: false,
        experience: "+10 лет опыта в преподавании",
        teacher: "Бахтияр, учитель",
        points: "IELTS 10.0",
        specialist: "Магистр педагогических наук",
        src: require('@/assets/img/main/teacher-1.png'),
        color: { backgroundColor:"#5FC5FF" }
      },
    {   title: "Elementary",
        info: "Beginner является твердым фундаментом, который пригодится для всех последующих уровней",
        learn: ["Алфавиту", "Как правильно произносить звуки", "Понимать английскую речь", "Говорить на простые темы", "Самостоятельно читать изи тексты", "Как использовать простые выражения", "Как строить диалоги в жизни", "Самостоятельно писать простые предложения путём использования вокабуляра и грамматики", "Развишь в себе личностные качества и любознательость"],
        syllabus: ["Parts of speech", "Nouns Verbs", "Adjectives Numerals", "Adverbs Personal Pronouns", "Subject Pronouns", "Object Pronouns To be", "am is are", "Possesive abjectivess", "Articles Countable and Uncountable nouns", "Singular an Plural nouns"] ,
        open: false,
        experience: "+10 лет опыта в преподавании",
        teacher: "Бахтияр, учитель",
        points: "IELTS 10.0",
        specialist: "Магистр педагогических наук",
        src: require('@/assets/img/main/teacher-2.png'),
        color: { backgroundColor:"#D095FF" }
    },
    {   title: "Pre-Intermedaite",
        info: "Beginner является твердым фундаментом, который пригодится для всех последующих уровней",
        learn: ["Алфавиту", "Как правильно произносить звуки", "Понимать английскую речь", "Говорить на простые темы", "Самостоятельно читать изи тексты", "Как использовать простые выражения", "Как строить диалоги в жизни", "Самостоятельно писать простые предложения путём использования вокабуляра и грамматики", "Развишь в себе личностные качества и любознательость"],
        syllabus: ["Parts of speech", "Nouns Verbs", "Adjectives Numerals", "Adverbs Personal Pronouns", "Subject Pronouns", "Object Pronouns To be", "am is are", "Possesive abjectivess", "Articles Countable and Uncountable nouns", "Singular an Plural nouns"] ,
        open: false,
        experience: "+10 лет опыта в преподавании",
        teacher: "Бахтияр, учитель",
        points: "IELTS 10.0",
        specialist: "Магистр педагогических наук",
        src: require('@/assets/img/main/teacher-3.png'),
        color: { backgroundColor:"#F8C94D" }
    },
    {   title: "Intermedaite",
        info: "Beginner является твердым фундаментом, который пригодится для всех последующих уровней",
        learn: ["Алфавиту", "Как правильно произносить звуки", "Понимать английскую речь", "Говорить на простые темы", "Самостоятельно читать изи тексты", "Как использовать простые выражения", "Как строить диалоги в жизни", "Самостоятельно писать простые предложения путём использования вокабуляра и грамматики", "Развишь в себе личностные качества и любознательость"],
        syllabus: ["Parts of speech", "Nouns Verbs", "Adjectives Numerals", "Adverbs Personal Pronouns", "Subject Pronouns", "Object Pronouns To be", "am is are", "Possesive abjectivess", "Articles Countable and Uncountable nouns", "Singular an Plural nouns"] ,
        open: false,
        experience: "+10 лет опыта в преподавании",
        teacher: "Бахтияр, учитель",
        points: "IELTS 10.0",
        specialist: "Магистр педагогических наук",
        src: require('@/assets/img/main/teacher-4.png'),
        color: { backgroundColor:"#3EC965" }
    },
    {   title: "Upper-Intermedaite",
        info: "Beginner является твердым фундаментом, который пригодится для всех последующих уровней",
        learn: ["Алфавиту", "Как правильно произносить звуки", "Понимать английскую речь", "Говорить на простые темы", "Самостоятельно читать изи тексты", "Как использовать простые выражения", "Как строить диалоги в жизни", "Самостоятельно писать простые предложения путём использования вокабуляра и грамматики", "Развишь в себе личностные качества и любознательость"],
        syllabus: ["Parts of speech", "Nouns Verbs", "Adjectives Numerals", "Adverbs Personal Pronouns", "Subject Pronouns", "Object Pronouns To be", "am is are", "Possesive abjectivess", "Articles Countable and Uncountable nouns", "Singular an Plural nouns"] ,
        open: false,
        experience: "+10 лет опыта в преподавании",
        teacher: "Бахтияр, учитель",
        points: "IELTS 10.0",
        specialist: "Магистр педагогических наук",
        src: require('@/assets/img/main/teacher-5.png'),
        color: { backgroundColor:"#F94848" }
    }
  ]
